name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start Docker Compose services
        run: |
          docker compose up -d --build
          sleep 10

      - name: Wait for DB to be ready
        run: |
          until docker compose exec db pg_isready -U postgres -d parking_db; do
            sleep 5
          done

      - name: Run migrations
        run: |
          docker compose exec web python manage.py migrate

      - name: Populate database
        run: |
          docker compose exec web python manage.py create_parking_spots 50

      - name: Run tests
        run: |
          docker compose exec web python manage.py test

      - name: Shut down Docker Compose
        run: docker compose down
