name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: parking_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker compose build

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Wait for DB to be ready
        run: docker compose exec db pg_isready -U postgres

      - name: Apply migrations
        run: docker compose exec web python manage.py migrate

      - name: Populate database
        run: docker compose exec web python manage.py create_parking_spots 50

      - name: Run tests
        run: docker compose exec web python manage.py test

      - name: Shut down Docker Compose
        run: docker compose down
